
// Domain models reflecting the "Genius Engine" protocols

export enum LearningPhase {
  INGESTION = 'INGESTION',         // Phase 1: Noise suppression & sourcing
  SCOPING = 'SCOPING',             // Phase 2: Outcome agreement
  SPRINT = 'SPRINT',               // Phase 3: The 10m Sprint
  CONSOLIDATION = 'CONSOLIDATION', // NSDR / Rest
}

export enum SessionStatus {
  IDLE = 'IDLE',
  FOCUS = 'FOCUS',         // Active learning
  ZEN_PULSE = 'ZEN_PULSE', // 10s Micro-reset (Input Lockdown)
  RETRIEVAL = 'RETRIEVAL', // 2m Quiz
  COMPLETED = 'COMPLETED'
}

export interface LearningSection {
  title: string;
  content: string; // Markdown
  imageKeyword: string;
  interactionType: 'READ' | 'REFLECTION';
}

// User Profiling
export interface UserPreferences {
  learningStyle: 'Visual' | 'Textual' | 'Interactive';
  motivationTrigger: 'Goal-Oriented' | 'Curiosity' | 'Fear-of-Missing-Out';
  attentionSpan: 'Deep Dive' | 'Rapid Fire' | 'Pomodoro';
  complexityPreference: 'First Principles' | 'Metaphorical' | 'Case Study';
}

// Scoping & Goal Setting
export type GoalPriority = 'Critical' | 'Useful' | 'Interesting';

export interface ScopedGoal {
  id: string;
  text: string;
  isSelected: boolean;
  priority: GoalPriority;
}

export interface ScopingData {
  complexity: string;
  thresholdConcepts: string[];
  goals: ScopedGoal[];
}

// Represents a "Digital Learning Object" (DLO)
export interface LearningUnit {
  id: string;
  title: string;
  duration: number; // in minutes
  complexity: string;
  motivatingStatement: string; // New: Derived from priming
  smartGoals: string[]; // Finalized goals
  thresholdConcepts: string[]; // key concepts for 80/20 scaffolding
  sections: LearningSection[]; // Replaces single content string
  wordPairs: Array<{a: string, b: string}>; // For Zen Pulse
  quiz: RetrievalQuestion[];
}

export interface RetrievalQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string; // Feedback loop
}

// New: Multi-Sprint Learning Program
export interface LearningProgram {
  id: string;
  topic: string; // The main subject (e.g., "Quantum Physics")
  sourceUrl?: string; // Original URL if the topic was a link
  syllabus: string[]; // The 7 session titles generated by AI
  currentSessionIndex: number; // 0 to 6
  status: 'ACTIVE' | 'COMPLETED';
  lastEngagedAt: number;
  progress: number; // 0-100
}

export interface UserState {
  name: string; // User's designation
  elevation: number; // 0-100% Mastery
  streak: number;
  currentSubject: string | null;
  activeProgramId: string | null; // Currently selected program
  preferences: UserPreferences; // Stored preferences
  dismissedExplainers: string[]; // IDs of dismissed help boxes
}

export interface SprintConfig {
  topic: string;
  durationMinutes: number; // usually 10
  complexityLevel: 'Beginner' | 'Intermediate' | 'Expert';
}

// New Interface for recording session details
export interface SprintLog {
  id: string;
  timestamp: number;
  topicInput: string; // URL or Topic
  primingAnswers: {
    relevance: string;
    relation: string;
    scope: string;
  };
  learningUnitId?: string;
}

// Debug Log Entry
export interface LogEntry {
  id: string;
  timestamp: number;
  type: 'info' | 'request' | 'response' | 'error';
  message: string;
  data?: any;
}